services:
  - type: web
    name: ecommerce-django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ecommerce.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
